### ISSUE TITLE
Nose tests cannot find data set files

### ISSUE THREAD

**Issue by wesbarnett** [choderalab/pymbar#243] opened 2016-12-31 03:01 UTC
The nose tests seem to expect the data sets from https://github.com/choderalab/pymbar-datasets to be in a directory in my home folder named `pymbar_data`. However, it seems like some of the files are not matching up. Here is my output from those tests (I assume the first two go with these data sets as well):

    pymbar.tests.test_covariance.test_gas ... SKIP: skip
    pymbar.tests.test_covariance.test_8proteins ... SKIP: skip

    pymbar.tests.test_mbar_solvers.test_gas ... SKIP: Cannot load dataset; skipping test.  Try downloading pymbar-datasets GitHub repository and setting PYMBAR-DATASETS environment variable.  Error was '``/home/wes/pymbar_data/gas-properties/gas-properties.h5`` does not exist'
    pymbar.tests.test_mbar_solvers.test_8proteins ... SKIP: Cannot load dataset; skipping test.  Try downloading pymbar-datasets GitHub repository and setting PYMBAR-DATASETS environment variable.  Error was '``/home/wes/pymbar_data/8proteins/8proteins.h5`` does not exist'

I can't find `gas-properties.h5` or `8proteins.h5` in the pymbar-datasets git repo.

**Comment by jchodera** [comment] 2016-12-31 14:08
Those datasets are in http://github/choderalab/pymbar-datasets

Full integration of these datasets into the testing and timing framework was underway by @kyleabeauchamp before the project was abandoned.

I don't think that there's a way to actually have these large tests complete in time in travis, but I'll give it a try.

**Comment by jchodera** [comment] 2016-12-31 14:20
I've also added documentation on how to grab the large datasets (to "Getting Started") if you want to test them yourself!

**Comment by wesbarnett** [comment] 2016-12-31 14:51
I followed that procedure (clone the pymbar-datasets repo to $HOME/pymbar_data) but the `.h5` files are missing. Is there some processing I need to perform on the data sets? Thanks!

**Comment by jchodera** [comment] 2016-12-31 15:01
Looks like those were never checked in by @kyleabeauchamp, but the scripts to generate the HDF5 files are checked in. Let me try doing that.

**Comment by jchodera** [comment] 2016-12-31 16:17
We're going to remove those tests until we have someone who is willing to maintain working versions of them. Thanks for pointing this out!

**Closed by jchodera** 2016-12-31 16:17 UTC

**Comment by mrshirts** [comment] 2016-12-31 16:31
>  gas-properties.h5 or 8proteins.h5 in the pymbar-datasets git repo.

I think that these were things that Kyle was trying to add - I added the gas-properties and 8proteins examples originally, as examples of real-life things that collaborators were using MBAR for.  The flat-text original scripts worked fine at the time they were committed. 

I don't know that we need nose-tests on examples, as they are examples, not core code, and presumably they would take a while to complete, as they are realistic problems, not modular code designed for reuse.  All we would really expect is that if someone followed the README and ran the scripts, they would be able to reproduce the results.

**Comment by jchodera** [comment] 2016-12-31 16:37
> I don't know that we need nose-tests on examples, as they are examples, not core code, and presumably they would take a while to complete, as they are realistic problems, not modular code designed for reuse. All we would really expect is that if someone followed the README and ran the scripts, they would be able to reproduce the results.

And they would not be able to, because the code was broken and not fully documented.

Even if they are examples, there should still be some continuous integration mechanism in place that tests to make sure they *still work* despite changes to `pymbar` or upstream tools (such as `pytables`). Without this and nobody to maintain them, they are no longer useful here.
